name: test

on:
  push:
    branches:
      - master
      - '*x'
    tags:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    # Weekly Monday 9AM build
    - cron: "0 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      default_python: "3.12"
      envs: |
        - linux: check-style
        - linux: check-security
        - linux: check-dependencies
  data:
    uses: ./.github/workflows/data.yml
  crds_contexts:
    uses: spacetelescope/crds/.github/workflows/contexts.yml@master
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    needs: [ data, crds_contexts ]
    with:
      setenv: |
        WEBBPSF_PATH: ${{ needs.data.outputs.webbpsf_path }}
        CRDS_PATH: ${{ needs.data.outputs.path }}/crds_cache
        CRDS_SERVER_URL: https://jwst-crds.stsci.edu
        CRDS_CLIENT_RETRY_COUNT: 3
        CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
      cache-path: ${{ needs.data.outputs.path }}
      cache-key: data-${{ needs.data.outputs.webbpsf_hash }}-${{ needs.crds_contexts.outputs.roman }}
      cache-restore-keys: webbpsf-${{ needs.data.outputs.webbpsf_hash }}
      envs: |
        - linux: py39-oldestdeps-xdist-cov
          pytest-results-summary: true
        - linux: py39-xdist
        - linux: py310-xdist
        - linux: py311-xdist
          pytest-results-summary: true
        - macos: py311-xdist
          pytest-results-summary: true
        - linux: py311-xdist-cov
          coverage: codecov
          pytest-results-summary: true
        - linux: py312-xdist
