name: CI

on:
  push:
    branches:
      - master
      - '*x'
    tags:
      - '*'
  pull_request:
    branches:
      - master
  schedule:
    # Weekly Monday 9AM build
    - cron: "0 9 * * 1"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  webbpsf:
    name: retrieve WEBBPSF data
    runs-on: ubuntu-latest
    env:
      WEBBPSF_PATH: /tmp/webbpsf
      WEBBPSF_SERVER_URL: https://stsci.box.com/shared/static/qxpiaxsjwo15ml6m4pkhtk36c9jgj70k.gz
    outputs:
      path: ${{ steps.path.outputs.path }}
      server: ${{ steps.server.outputs.server }}
      hash: ${{ steps.data.outputs.hash }}
    steps:
      - id: path
        run: echo "path=${{ env.WEBBPSF_PATH }}" >> $GITHUB_OUTPUT
      - id: server
        run: echo "server=${{ env.WEBBPSF_SERVER_URL }}" >> $GITHUB_OUTPUT
      - id: data
        run: |
          mkdir -p ${{ steps.path.outputs.path }}
          wget ${{ steps.server.outputs.server }} -O ${{ steps.path.outputs.path }}/webbpsf-data.tar.gz
          cd ${{ steps.path.outputs.path }}
          tar --strip-components=1 -xzvf webbpsf-data.tar.gz
          echo "hash=$( shasum webbpsf-data.tar.gz | awk '{ print $1 }' )" >> $GITHUB_OUTPUT
      - uses: actions/cache@v3
        with:
          path: ${{ steps.path.outputs.path }}
          key: data-${{ steps.data.outputs.hash }}
  crds:
    name: retrieve current CRDS context
    runs-on: ubuntu-latest
    env:
      OBSERVATORY: jwst
      CRDS_PATH: /tmp/crds_cache
      CRDS_SERVER_URL: https://jwst-crds.stsci.edu
    steps:
      - id: context
        run: >
          echo "pmap=$(
          curl -s -X POST -d '{"jsonrpc": "1.0", "method": "get_default_context", "params": ["${{ env.OBSERVATORY }}"], "id": 1}' ${{ env.CRDS_SERVER_URL }}/json/ |
          python -c "import sys, json; print(json.load(sys.stdin)['result'])"
          )" >> $GITHUB_OUTPUT
        # Get default CRDS_CONTEXT without installing crds client
        # See https://hst-crds.stsci.edu/static/users_guide/web_services.html#generic-request
      - id: path
        run: echo "path=${{ env.CRDS_PATH }}" >> $GITHUB_OUTPUT
      - id: server
        run: echo "url=${{ env.CRDS_SERVER_URL }}" >> $GITHUB_OUTPUT
    outputs:
      context: ${{ steps.context.outputs.pmap }}
      path: ${{ steps.path.outputs.path }}
      server: ${{ steps.server.outputs.url }}
  check:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@v1
    with:
      envs: |
        - linux: check-style
        - linux: check-security
        - linux: check-dependencies
        - linux: build-dist
  test:
    uses: OpenAstronomy/github-actions-workflows/.github/workflows/tox.yml@main
    needs: [ crds, webbpsf ]
    with:
      setenv: |
        CRDS_PATH: ${{ needs.crds.outputs.path }}
        CRDS_SERVER_URL: ${{ needs.crds.outputs.server }}
        CRDS_CLIENT_RETRY_COUNT: 3
        CRDS_CLIENT_RETRY_DELAY_SECONDS: 20
        WEBBPSF_PATH: ${{ needs.webbpsf.outputs.path }}
      cache-path: |
        ${{ needs.crds.outputs.path }}
        ${{ needs.webbpsf.outputs.path }}
      cache-key: crds-${{ needs.crds.outputs.context }}-${{ needs.webbpsf.outputs.hash }}
      envs: |
        - linux: py39-oldestdeps-xdist-cov
          pytest-results-summary: true
        - linux: py39-xdist
        - linux: py39-sdpdeps-xdist
        - linux: py310-xdist
        - linux: py311-xdist
        - macos: py311-xdist
          pytest-results-summary: true
        - linux: py311-devdeps-xdist
        - linux: py311-xdist-cov
          coverage: codecov
          pytest-results-summary: true
